version: '3.8'

services:
  master:
    container_name: centalki_master
    image: centalki-master
    environment:
      - NODE_ENV=production
      - PORT=4000
      - RAPID_API_KEY=a8bf900b67msh9320c0c4a3c035fp1be8b1jsnf1bfaa1f3fe5
      - PHONETIC_ENDPOINT=https://api.dictionaryapi.dev/api/v2/entries/en
      - EXAMPLE_ENDPOINT=https://mashape-community-urban-dictionary.p.rapidapi.com/define
      - TRANSLATION_ENDPOINT=https://ai-translate.p.rapidapi.com/translates
      - GOOGLE_APPLICATION_CREDENTIALS=../../service-account-file.json

    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:4000
    networks:
      - master-network
    restart: unless-stopped
  master-staging:
    container_name: centalki_master_staging
    image: centalki-master-staging
    environment:
      - NODE_ENV=staging
      - PORT=8000
      - RAPID_API_KEY=a8bf900b67msh9320c0c4a3c035fp1be8b1jsnf1bfaa1f3fe5
      - PHONETIC_ENDPOINT=https://api.dictionaryapi.dev/api/v2/entries/en
      - EXAMPLE_ENDPOINT=https://mashape-community-urban-dictionary.p.rapidapi.com/define
      - TRANSLATION_ENDPOINT=https://ai-translate.p.rapidapi.com/translates
      - GOOGLE_APPLICATION_CREDENTIALS=../../service-account-file.json

    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    networks:
      - master-network
    restart: unless-stopped

  master-development:
    container_name: centalki_master_development
    image: centalki-master-development
    volumes:
      - .:/app
      # - ./app/node_modules
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - PORT=9229
      - RAPID_API_KEY=a8bf900b67msh9320c0c4a3c035fp1be8b1jsnf1bfaa1f3fe5
      - PHONETIC_ENDPOINT=https://api.dictionaryapi.dev/api/v2/entries/en
      - EXAMPLE_ENDPOINT=https://mashape-community-urban-dictionary.p.rapidapi.com/define
      - TRANSLATION_ENDPOINT=https://ai-translate.p.rapidapi.com/translates
      - GOOGLE_APPLICATION_CREDENTIALS=../../service-account-file.json
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:9229
    networks:
      - master-network
    restart: unless-stopped
networks:
  master-network:
# volumes:
#   myapp: 
    