version: '3.8'

services:
  master:
    container_name: centalki_master
    image: centalki-master
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    networks:
      - master-network
    restart: unless-stopped
networks:
  master-network:
