version: '3.8'

services:
  master:
    container_name: centalki_master
    image: centalki-master
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:4000
    networks:
      - master-network
    restart: unless-stopped
  master-staging:
    container_name: centalki_master_staging
    image: centalki-master-staging
    env_file: .env.staging
    environment:
      - NODE_ENV=production
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    networks:
      - master-network
    restart: unless-stopped

  master-development:
    container_name: centalki_master_development
    image: centalki-master-development
    volumes:
      - .:/app
      # - ./app/node_modules
    command: yarn start:dev
    env_file: .env.dev
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:9229
    networks:
      - master-network
    restart: unless-stopped
networks:
  master-network:
# volumes:
#   myapp: 
    