export enum EDifficulty {
  ELEMENTARY = 'ELEMENTARY',
  PRE_INTERMEDIATE = 'PRE_INTERMEDIATE',
  INTERMEDIATE = 'INTERMEDIATE',
  UPPER_INTERMEDIATE = 'UPPER_INTERMEDIATE',
  NOT_TOO_HARD = 'NOT_TOO_HARD',
  NOT_TOO_EASY = 'NOT_TOO_EASY',
  NOT_SURE = 'NOT_SURE',
}
